# Generated by Django 4.0.7 on 2022-12-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_looking_for',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_looking_for',
            name='licence_document',
            field=models.FileField(default='exit', upload_to='documents'),
            preserve_default=False,
        ),
    ]
