# Generated by Django 4.0.7 on 2022-12-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_product_looking_for_boolean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('duration', models.DateField()),
                ('quality', models.CharField(max_length=255)),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
