# Generated by Django 4.0.7 on 2022-12-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_specific_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_product',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
