# Generated by Django 4.0.7 on 2022-12-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_prediction_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_product',
            name='solution',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
