# Generated by Django 4.0.7 on 2022-12-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_specific_product_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_product',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='specific_product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
