# Generated by Django 4.0.7 on 2022-12-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_specific_product_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_product',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
    ]
