# Generated by Django 4.0.7 on 2022-12-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_specific_product_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_product',
            name='email',
            field=models.EmailField(default='exit', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
