# Generated by Django 4.0.7 on 2022-12-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_specific_product_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_product',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
