# Generated by Django 4.0.7 on 2022-12-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_pay_slip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pay_slip',
            new_name='Pay_slips',
        ),
    ]
