# Generated by Django 4.0.7 on 2023-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('f1', models.CharField(max_length=255)),
                ('f2', models.CharField(max_length=255)),
                ('f3', models.CharField(max_length=255)),
                ('f4', models.CharField(max_length=255)),
                ('f5', models.CharField(max_length=255)),
            ],
        ),
    ]
