# Generated by Django 4.0.7 on 2023-01-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='username',
            new_name='email',
        ),
    ]
