# Generated by Django 4.0.7 on 2023-01-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_loginattempt_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='pattern',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
