# Generated by Django 4.0.7 on 2023-01-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_details_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='a1',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='users_details',
            name='a2',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='users_details',
            name='a3',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='users_details',
            name='a4',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='users_details',
            name='a5',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
