# Generated by Django 4.0.7 on 2023-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_users_details_a1_users_details_a2_users_details_a3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
