# Generated by Django 4.0.7 on 2023-02-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_users_details_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_details',
            name='admin_status',
            field=models.BooleanField(default=False),
        ),
    ]
