# Generated by Django 4.0.7 on 2023-02-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_users_details_admin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
