# Generated by Django 4.0.7 on 2023-02-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_approve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_approve',
            name='status',
        ),
    ]
