# Generated by Django 4.0.7 on 2023-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_approve_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_approve',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
